<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    //     $productRecords = [
    //         ['id'=>1, 'section_id'=>2,'category_id'=>5, 'brand_id'=>5, 'admin_id'=>0, 'superadmin_id'=>1, 'user_id'=>1, 'superadmin_type'=>'admin','product_name'=>'Redmi Note 11','product_code'=>'AD335','product_color'=>'blue','product_price'=>2000,'product_discount'=>10,'product_weight'=>500,'product_image'=>'','product_video'=>'','description'=>'','meta_title'=>'','meta_description'=>'','meta_keyword'=>'','is_feature'=>'Yes','status'=>1],
    //         ['id'=>2, 'section_id'=>1,'category_id'=>8, 'brand_id'=>2, 'admin_id'=>1, 'superadmin_id'=>0, 'user_id'=>1, 'superadmin_type'=>'superadmin','product_name'=>'Red Casual T-Shirt','product_code'=>'DF453','product_color'=>'red','product_price'=>1200,'product_discount'=>20,'product_weight'=>200,'product_image'=>'','product_video'=>'','description'=>'','meta_title'=>'','meta_description'=>'','meta_keyword'=>'','is_feature'=>'Yes','status'=>1],
    //        ];
    //        Product::insert($productRecords);
    // }
    $productRecords = [
        [
            'id' => 1,
            'section_id' => 2,
            'category_id' => 5,
            'brand_id' => 5,
            'admin_id' => 0,
            'superadmin_id' => 1,
            'user_id' => 1,
            'superadmin_type' => 'admin',
            'product_name' => 'Redmi Note 11',
            'product_code' => 'AD335',
            'product_color' => 'blue',
            'product_price' => 2000,
            'product_discount' => 10,
            'product_weight' => 500,
            'product_image' => '',
            'product_video' => '',
            'description' => '',
            'meta_title' => '',
            'meta_description' => '',
            'meta_keyword' => '',
            'is_feature' => 'Yes',
            'status' => 1
        ],
        [
            'id' => 2,
            'section_id' => 1,
            'category_id' => 8,
            'brand_id' => 2,
            'admin_id' => 1,
            'superadmin_id' => 0,
            'user_id' => 1,
            'superadmin_type' => 'superadmin',
            'product_name' => 'Red Casual T-Shirt',
            'product_code' => 'DF453',
            'product_color' => 'red',
            'product_price' => 1200,
            'product_discount' => 20,
            'product_weight' => 200,
            'product_image' => '',
            'product_video' => '',
            'description' => '',
            'meta_title' => '',
            'meta_description' => '',
            'meta_keyword' => '',
            'is_feature' => 'Yes',
            'status' => 1
        ],
        [
            'id' => 3,
            'section_id' => 2,
            'category_id' => 5,
            'brand_id' => 3,
            'admin_id' => 0,
            'superadmin_id' => 2,
            'user_id' => 2,
            'superadmin_type' => 'admin',
            'product_name' => 'Samsung Galaxy S21',
            'product_code' => 'SGS21',
            'product_color' => 'black',
            'product_price' => 2500,
            'product_discount' => 15,
            'product_weight' => 400,
            'product_image' => '',
            'product_video' => '',
            'description' => '',
            'meta_title' => '',
            'meta_description' => '',
            'meta_keyword' => '',
            'is_feature' => 'No',
            'status' => 1
        ],
        [
            'id' => 4,
            'section_id' => 1,
            'category_id' => 8,
            'brand_id' => 1,
            'admin_id' => 2,
            'superadmin_id' => 0,
            'user_id' => 3,
            'superadmin_type' => 'superadmin',
            'product_name' => 'Blue Denim Jeans',
            'product_code' => 'BDJ223',
            'product_color' => 'blue',
            'product_price' => 1500,
            'product_discount' => 10,
            'product_weight' => 600,
            'product_image' => '',
            'product_video' => '',
            'description' => '',
            'meta_title' => '',
            'meta_description' => '',
            'meta_keyword' => '',
            'is_feature' => 'Yes',
            'status' => 1
        ],
        [
            'id' => 5,
            'section_id' => 2,
            'category_id' => 6,
            'brand_id' => 4,
            'admin_id' => 0,
            'superadmin_id' => 3,
            'user_id' => 4,
            'superadmin_type' => 'admin',
            'product_name' => 'Apple iPhone 13',
            'product_code' => 'IP13',
            'product_color' => 'white',
            'product_price' => 3000,
            'product_discount' => 5,
            'product_weight' => 450,
            'product_image' => '',
            'product_video' => '',
            'description' => '',
            'meta_title' => '',
            'meta_description' => '',
            'meta_keyword' => '',
            'is_feature' => 'No',
            'status' => 1
        ],
        [
            'id' => 6,
            'section_id' => 1,
            'category_id' => 9,
            'brand_id' => 2,
            'admin_id' => 3,
            'superadmin_id' => 0,
            'user_id' => 5,
            'superadmin_type' => 'superadmin',
            'product_name' => 'Green Sports Shoes',
            'product_code' => 'GSS67',
            'product_color' => 'green',
            'product_price' => 1800,
            'product_discount' => 20,
            'product_weight' => 700,
            'product_image' => '',
            'product_video' => '',
            'description' => '',
            'meta_title' => '',
            'meta_description' => '',
            'meta_keyword' => '',
            'is_feature' => 'Yes',
            'status' => 1
        ],
        [
            'id' => 7,
            'section_id' => 2,
            'category_id' => 5,
            'brand_id' => 5,
            'admin_id' => 0,
            'superadmin_id' => 4,
            'user_id' => 6,
            'superadmin_type' => 'admin',
            'product_name' => 'OnePlus Nord',
            'product_code' => 'OPN23',
            'product_color' => 'grey',
            'product_price' => 2200,
            'product_discount' => 10,
            'product_weight' => 420,
            'product_image' => '',
            'product_video' => '',
            'description' => '',
            'meta_title' => '',
            'meta_description' => '',
            'meta_keyword' => '',
            'is_feature' => 'No',
            'status' => 1
        ],
        [
            'id' => 8,
            'section_id' => 1,
            'category_id' => 7,
            'brand_id' => 3,
            'admin_id' => 4,
            'superadmin_id' => 0,
            'user_id' => 7,
            'superadmin_type' => 'superadmin',
            'product_name' => 'Black Leather Jacket',
            'product_code' => 'BLJ789',
            'product_color' => 'black',
            'product_price' => 3500,
            'product_discount' => 25,
            'product_weight' => 1200,
            'product_image' => '',
            'product_video' => '',
            'description' => '',
            'meta_title' => '',
            'meta_description' => '',
            'meta_keyword' => '',
            'is_feature' => 'Yes',
            'status' => 1
        ],
        [
            'id' => 9,
            'section_id' => 2,
            'category_id' => 5,
            'brand_id' => 1,
            'admin_id' => 0,
            'superadmin_id' => 5,
            'user_id' => 8,
            'superadmin_type' => 'admin',
            'product_name' => 'Sony WH-1000XM4',
            'product_code' => 'SWHXM4',
            'product_color' => 'black',
            'product_price' => 3000,
            'product_discount' => 15,
            'product_weight' => 300,
            'product_image' => '',
            'product_video' => '',
            'description' => '',
            'meta_title' => '',
            'meta_description' => '',
            'meta_keyword' => '',
            'is_feature' => 'No',
            'status' => 1
        ],
        [
            'id' => 10,
            'section_id' => 1,
            'category_id' => 10,
            'brand_id' => 2,
            'admin_id' => 5,
            'superadmin_id' => 0,
            'user_id' => 9,
            'superadmin_type' => 'superadmin',
            'product_name' => 'White Sneakers',
            'product_code' => 'WSN123',
            'product_color' => 'white',
            'product_price' => 1700,
            'product_discount' => 5,
            'product_weight' => 500,
            'product_image' => '',
            'product_video' => '',
            'description' => '',
            'meta_title' => '',
            'meta_description' => '',
            'meta_keyword' => '',
            'is_feature' => 'Yes',
            'status' => 1
        ]
    ];

    Product::insert($productRecords);
}
}